table 'Sheet1 (7)'
	lineageTag: 41e9bc4c-e9a8-446e-bef0-2795cc841575

	column 'PELAPORAN PBD (JULAI 2024)'
		dataType: string
		lineageTag: a78e04d5-b6bc-44ba-90a4-3f8b9963b031
		summarizeBy: none
		sourceColumn: PELAPORAN PBD (JULAI 2024)

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 6a5a3d49-91ad-4f98-aa5b-4572bac886cc
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: db3a525f-3db9-4db4-a03e-ed490d9060df
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 05a71bc4-4847-4d98-b384-de1c0ac17f74
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: fbf48402-4211-4968-97a4-11c98271a255
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 98424922-f4b6-4a35-a309-d6326453616d
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 279d2951-93c0-4e06-b458-7f4b5d546641
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 8738a838-60f9-4ff7-85dd-a5dc98620641
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 7ea3c8e6-403c-43ff-9c73-903e607e8d10
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: f82218e5-942b-4937-aac1-f037bf6c2b71
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: 760a176d-5ce7-4f67-987e-4895328e8f7d
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 2e038c7a-d854-412d-b9ad-52c9d9d46844
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 5b73f6a1-ee8f-4c65-b0ac-d295926f4772
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: 11c22ce3-991d-45c6-86e8-81cda9f6a6f4
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 46b7c6a0-1883-41a6-b5ff-43b1a5d8ab26
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1 (7)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\soulr\OneDrive\Documents\POWER BI DOC\PBD JULAI 2024 TAHAP 2.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"PELAPORAN PBD (JULAI 2024)", type any}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

