table 'Sheet1 (6)'
	lineageTag: 82a96f09-a1fb-4f23-9a57-b0ffbc8d4cc4

	column 'PELAPORAN PBD (JULAI 2024)'
		dataType: string
		lineageTag: ded1522e-8514-4eed-a81b-3b228c652e9d
		summarizeBy: none
		sourceColumn: PELAPORAN PBD (JULAI 2024)

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 02dbbe99-a387-46c1-bf2b-6391dd3b5cfc
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 6504769f-e6c4-4ece-9503-8f665b2cd34a
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: b17b25e6-9ffb-41f1-9e7f-6675370b2e20
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 7f1255d7-f4e1-4c60-9f29-5210ec68880d
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 2d56c8bf-d9ca-4b24-a2d3-97991497997d
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 7f18ee9c-4542-4df6-847a-d3b9b9e345b1
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 84eaa80f-caab-41bf-8158-f74e3a478c43
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: c7e804ba-5341-42e6-ab7c-192db7bc85fc
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: b77287f2-3308-44df-a634-ef9bb45af6e3
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: 450ba2f1-d223-420f-b27b-3da428195ab9
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 32c0fc21-9ac8-421e-a795-e153d281c4e0
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 626d26af-7117-4a85-8f1b-7b5a6618a27d
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: 285a90d5-c85e-48c7-8e60-76f56767df93
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1 (6)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\soulr\OneDrive\Documents\POWER BI DOC\PBD JULAI 2024 TAHAP 1.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"PELAPORAN PBD (JULAI 2024)", type any}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

